#!/bin/bash

set -ex

kernel="$1"
root_part="$2"

bootctl --path=/boot install

cat > /boot/loader/loader.conf <<EOF
default arch.conf
timeout 3
console-mode max
editor no
EOF

cat > /boot/loader/entries/arch.conf <<EOF
title Arch Linux
linux /vmlinuz-${kernel}
initrd /amd-ucode.img
initrd /intel-ucode.img
initrd /initramfs-${kernel}.img
options root=$root_part rootflags=subvol=@root rw
EOF
