#!/bin/bash

set -ex

bootctl --path=/boot install

cat > /boot/loader/loader.conf <<EOF
default arch.conf
timeout 3
console-mode max
editor no
EOF

uuid="$(blkid -s UUID -o value "${1}2")"

cat > /boot/loader/entries/arch.conf <<EOF
title Arch Linux
linux /vmlinuz-linux
initrd /amd-ucode.img
initrd /intel-ucode.img
initrd /initramfs-linux.img
options cryptdevice=UUID=${uuid}:luks:allow-discards root=/dev/mapper/luks rootflags=subvol=@root rd.luks.options=discard rw
EOF
