#!/bin/bash

set -ex

kernel="$1"
root_part="$2"

bootctl --path=/boot install

cat > /boot/loader/loader.conf <<EOF
default arch.conf
timeout 3
console-mode max
editor no
EOF

uuid="$(blkid -s UUID -o value "$root_part")"

cat > /boot/loader/entries/arch.conf <<EOF
title Arch Linux
linux /vmlinuz-${kernel}
initrd /amd-ucode.img
initrd /intel-ucode.img
initrd /initramfs-${kernel}.img
options cryptdevice=UUID=${uuid}:luks:allow-discards root=/dev/mapper/luks rootflags=subvol=@root rd.luks.options=discard rw
EOF
