#!/bin/bash

set -ex

disk="$1"

# EFI/boot partition
sgdisk --new=1:0:+512M "$disk"
sgdisk --typecode=1:ef00 "$disk"

# EFI/boot filesystem
mkfs.vfat -F 32 -n EFI "${disk}1"

# Root partition
sgdisk --largest-new=2 "$disk"
sgdisk --typecode=2:8304 "$disk"
