#!/bin/bash

cat > /usr/lib/systemd/network/20-ether.network << EOF
[Match]
Type=ether

[Network]
DHCP=yes
EOF

systemctl enable systemd-networkd.service
systemctl enable systemd-resolved.service
systemctl enable sshd.service
