---
name: Code Quality

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run shellcheck
        run: find . -type f -executable ! -path './.git*' -print -exec shellcheck --color=always {} \+
